export const GET_CARS_LOADING = "GET_CARS_LOADING";
export const REMOVE_CARS = "REMOVE_CARS";
export const ADD_CARS_FAVOURITE= "ADD_CARS_FAVOURITE";
export const ADD_CARS_SUCCESS = "ADD_CARS_SUCCESS";
export const ADD_CARS_ERROR = "ADD_CARS_ERROR";
export const GET_CARS_FAVOURITE = "GET_CARS_FAVOURITE";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_ERROR = "GET_CARS_ERROR";
